### PR TITLE
marked as submodule

### PR DESCRIPTION
**Pull request by SeriousM**
hi, I just updated the package to just use mared as a submodule instead the copied marked.js.
could you please just update your package?
thanks!

### CODE REVIEW

**Comment by perak** [comment]
Done. Thank you! :+1:

**Comment by SeriousM** [comment]
it was a pleasure! I hope the package is compilable?

**Comment by perak** [comment]
Sure, it's on atmosphere already (and I updated 2 apps using markdown to test - it works normally).

P.S. I listed you in README.md

**Comment by perak** [comment]
(just update one that is online: http://generator-markdowned.meteor.com/ )

**Pull request merged**
